### ISSUE TITLE
Add example github action to host as github pages

### ISSUE THREAD

**Issue by bircher** [drupalpod/drupalpod-tome-starterkit#1]
This is a fabulous contraption!
I just found this from https://www.drupal.org/project/ideas/issues/3230448#comment-14280222

All it needs is a template github action that (generates the static site with tome if not already done in gitpod and) publishes the static site in a github page.

Then the workflow is complete! When you want to edit the site you spin it up in gitpod, you save the content, export it and generate the static site, commit everything. Then github updates the site.

**Comment by Decipher** [comment]
Hi @bircher,

I have a Druxt version of this template for Decoupled/Serverless Drupal with Nuxt.js, and I would definitely like to investigate GitHub actions for that project.

If you have any resources or example workflows, please provide some links. And PRs very welcomed.

**Comment by mortenson** [comment]
tome-project now includes an example build for GitHub pages (and netlify in another file): https://github.com/drupal-tome/tome-project/blob/master/.example_github/workflows/build.yml

For a "real life" version, you can see how my site is built: https://github.com/mortenson/mortenson.github.io/blob/develop/.github/workflows/build.yml

**Comment by Decipher** [comment]
I've added a a version based of @mortenson's workflows and other workflows I have in place: https://github.com/drupalpod/drupalpod-tome-starterkit/blob/main/.github/workflows/main.yml

You can see the deployed page @ https://drupalpod.github.io/drupalpod-tome-starterkit/

**Comment by bircher** [comment]
amazing! I haven't had time to follow this but I will give it a go hopefully soon!
